#!/bin/bash
clear
PROCCOUNT=`ps -Afl | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 5`
echo -e "\033[1;31m
`figlet Pulshen`
Welcome.. to real world...
\033[0;31m--------------------: \033[0;3mSystem Data\033[0;31m :--------------------
\033[0;31m+   \033[0;37mAddress \033[0;31m= \033[1;33mpulshen.github.io
\033[0;31m+    \033[0;37mKernel \033[0;31m= \033[1;33m`uname -r`
\033[0;31m+    \033[0;37mUptime \033[0;31m= \033[1;33m`uptime | sed 's/.*up ([^,]*), .*/1/'`
\033[0;31m+       \033[0;37mCPU \033[0;31m= \033[1;33mWrite your CPU info there
\033[0;31m+    \033[0;37mMemory \033[0;31m= \033[1;33m`cat /proc/meminfo | grep MemTotal | awk {'print $2'}` kB
\033[0;31m--------------------: \033[0;37mUser Data\033[0;31m :--------------------
\033[0;37m Username \033[0;37m= \033[1;37m`whoami`
\033[0;37m \033[0;37mProcesses \033[0;37m= \033[1;33m$PROCCOUNT of `ulimit -u` MAX
\033[0;31m--------------------: \033[0;37mServices Tab\033[0;31m :----------------
\033[0;31m+    \033[0;37m MySQL \033[0;31m= \033[1;33m `sudo service mysql status | grep "mysql" | awk {'print $2'}`
\033[0;31m+    \033[0;37mApache \033[0;31m= \033[1;33m `sudo service apache2 status | grep "apache2" | awk {'print $4'}`
\033[0;31m+    \033[0;37m Samba \033[0;31m= \033[1;33m`sudo service smbd status | grep -E "(start/running|stop/waiting)" | cut -c 5-19`
\033[0;31m+    \033[0;37mTSpeak \033[0;31m= \033[1;33m `sudo service teamspeak3 status`
\033[0;37m
"
