#!/bin/bash
echo -e "\033[1;31m
`clear`
`figlet UBUNTU`
Go fuck yourself..._
\033[0;31m--------------------: \033[0;3mSystem Data\033[0;31m :--------------------
\033[0;31m+   \033[0;37mAddress \033[0;31m= \033[1;33m lexforceterror.homenet.org
\033[0;31m+    \033[0;37mKernel \033[0;31m= \033[1;33m `uname -r` Processor `uname -p`
\033[0;31m+    \033[0;37mUptime \033[0;31m= \033[1;33m `uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'`
\033[0;31m+    \033[0;37mTLUSRS \033[0;31m= \033[1;33m `uptime | grep -ohe '[0-9.*] user[s,]'`
\033[0;31m+    \033[0;37mAGLoad \033[0;31m= \033[1;33m `uptime | grep -ohe 'load average[s:][: ].*' | awk '{ print $3 }'`
\033[0;31m+       \033[0;37mCPU \033[0;31m= \033[1;33m Pentium(R) Dual-Core CPU E5200 @ 2.50GHz, 2 cores
\033[0;31m+    \033[0;37mMemory \033[0;31m= \033[1;33m `cat /proc/meminfo | grep MemTotal | awk {'print $2'}` kB
\033[0;31m--------------------: \033[0;37mServices Status\033[0;31m :----------------
\033[0;31m+    \033[0;37m MySQL \033[0;31m= \033[1;33m `sudo service mysql status | grep "mysql" | awk {'print $2'}`
\033[0;31m+    \033[0;37mApache \033[0;31m= \033[1;33m `sudo service apache2 status | grep "apache2" | awk {'print $4'}`
\033[0;31m+    \033[0;37m Samba \033[0;31m= \033[1;33m`sudo service smbd status | grep -E "(start/running|stop/waiting)" | cut -c 5-19`
\033[0;31m+    \033[0;37mTSpeak \033[0;31m= \033[1;33m `sudo service teamspeak3 status`
\033[0;31m+    \033[0;37m  Plex \033[0;31m= \033[1;33m `sudo service plexmediaserver status | grep -E "(start/running|stop/waiting)" | cut -c 17-29`
\033[0;37m
"
